import type { Port } from "@/lib/ports/schema";

export const originalSystemById: Record<Port["id"], string> = {
  sm64ex: "Nintendo 64",
  "ship-of-harkinian": "Nintendo 64",
  "2ship2harkinian": "Nintendo 64",
  "star-rod": "Nintendo 64",
  "open-lara": "PlayStation / Sega Saturn",
  devilutionx: "MS-DOS",
  "nxengine-evo": "Microsoft Windows",
  "daggerfall-unity": "MS-DOS",
  openmw: "Microsoft Windows",
  "xash3d-fwgs": "Microsoft Windows",
  vkquake: "MS-DOS",
  "yamagi-quake2": "Microsoft Windows",
  gzdoom: "MS-DOS",
  eduke32: "MS-DOS",
  openxcom: "MS-DOS / Amiga",
  openttd: "MS-DOS / Amiga",
  openrct2: "Microsoft Windows",
  "fallout1-ce": "MS-DOS",
  "fallout2-ce": "Microsoft Windows",
  openjk: "Microsoft Windows",
  gemrb: "Microsoft Windows / MS-DOS",
  "sonic-1-2-2013": "Sega Mega Drive / Genesis",
  "sonic-mania-decomp": "Microsoft Windows",
  "downpour-recomp": "Xbox 360",
  wiicompiled: "Wii",
  openra: "MS-DOS",
  starship: "Nintendo 64",
  spaghettikart: "Nintendo 64",
  lighthouse: "Nintendo 64",
  "goldeneye-64-recompiled": "Nintendo 64",
  "dk64-recompiled": "Nintendo 64",
  "wave-race-64-recompiled": "Nintendo 64",
  "road-rash-64-recompiled": "Nintendo 64",
  "f-zero-snes-recompiled": "Super Nintendo",
  "dkc-recompiled": "Super Nintendo",
  "metroid-prime-hunters-recompiled": "Nintendo DS",
  "perfect-dark-dabs-mod": "Nintendo 64",
  triaevum: "Nintendo 3DS",
  "prboom-plus-rt": "MS-DOS",
  "doom3-dude": "Microsoft Windows",
  "unleashed-recompiled": "Xbox 360",
  dusklight: "GameCube",
  "melee-native": "GameCube",
  pikmin: "Nintendo GameCube",
  petari: "Wii",
  "ctr-native": "PlayStation",
  pokered: "Game Boy",
  zelda3: "Super Nintendo",
  "dkr-r": "Nintendo 64",
  "symphony-recomp": "PlayStation",
  "super-mario-bros-remastered": "Nintendo Entertainment System",
  "crash-bandicoot": "PlayStation",
  "minish-cap": "Game Boy Advance",
  "marathon-recomp": "Xbox 360",
  dhewm3: "Microsoft Windows",
  ioquake3: "Microsoft Windows",
  "dxx-rebirth": "MS-DOS",
  julius: "Microsoft Windows",
  corsixth: "MS-DOS",
  vcmi: "MS-DOS / Microsoft Windows",
  fh2: "MS-DOS",
  openapoc: "MS-DOS / Microsoft Windows",
  openjazz: "MS-DOS",
  shockolate: "MS-DOS",
  opensage: "Microsoft Windows",
  openage: "MS-DOS / Microsoft Windows",
  "d1x-rebirth": "MS-DOS",
  raze: "MS-DOS",
  "arx-libertatis": "Microsoft Windows",
  opendune: "MS-DOS",
  "banjo-kazooie-recomp": "Nintendo 64",
  "castlevania-lod-recomp": "Nintendo 64",
  "pokemon-stadium-recomp": "Nintendo 64",
  "pilotwings-64-recomp": "Nintendo 64",
  "aleph-one": "Macintosh",
  "freedroid-classic": "Commodore 64",
  "conker-bad-fur-day-recomp": "Nintendo 64",
  "harvest-moon-64-recomp": "Nintendo 64",
  "pokemon-snap-recomp": "Nintendo 64",
  "space-station-silicon-valley-recomp": "Nintendo 64",
  "super-mario-world-recomp": "Super Nintendo",
  "mega-man-x-snes-recomp": "Super Nintendo",
  "ogre-battle-64-recomp": "Nintendo 64",
  "quest-64-recomp": "Nintendo 64",
  "dinosaur-planet-recomp": "Nintendo 64",
  "bomberman-64-recomp": "Nintendo 64",
  "bomberman-hero-recomp": "Nintendo 64",
  "beetle-adventure-racing-recomp": "Nintendo 64",
  "chocolate-doom": "MS-DOS",
  "open-goal": "PlayStation 2",
  redriver2: "PlayStation",
  "wipeout-phantom-edition": "PlayStation",
  "rsdkv3-decompilation": "Sega CD / Mega-CD",
  keeperfx: "MS-DOS",
  ecwolf: "MS-DOS",
  "perfect-dark-port": "Nintendo 64",
  "lcs-recomp": "PlayStation Portable",
  psprecomp: "PlayStation Portable",
  "namco-system-22-prop-cycle": "Namco System 22",
  "namco-system-22-rave-racer": "Namco System 22",
  "namco-system-22-tokyo-wars": "Namco System 22",
  "namco-system-22-dirt-dash": "Namco System 22",
  "re-lcs": "PlayStation Portable",
  "zelda64-recomp": "Nintendo 64",
  "the-simpsons-game-recomp": "Xbox 360",
  "open-rw": "Microsoft Windows",
  "crispy-doom": "MS-DOS",
  doomretro: "MS-DOS",
  "dsda-doom": "MS-DOS",
  "eternity-engine": "MS-DOS",
  odamex: "MS-DOS",
  woof: "MS-DOS",
  "nugget-doom": "MS-DOS",
  "doom64-ex-plus": "Nintendo 64",
  "rbdoom-3-bfg": "Microsoft Windows",
  ironwail: "MS-DOS",
  darkplaces: "MS-DOS",
  quakespasm: "MS-DOS",
  etlegacy: "Microsoft Windows",
  "return-to-castle-wolfenstein": "Microsoft Windows",
  nblood: "MS-DOS",
  rottexpr: "MS-DOS",
  opentyrian: "MS-DOS",
  "doukutsu-rs": "Microsoft Windows",
  sdlpop: "MS-DOS",
  "the-force-engine": "MS-DOS",
  exult: "MS-DOS",
  openloco: "Microsoft Windows",
  "open-enroth": "Microsoft Windows",
  "open-gothic": "Microsoft Windows",
  openmohaa: "Microsoft Windows",
  "freespace-2": "Microsoft Windows",
  "vanilla-conquer": "MS-DOS",
  thyme: "Microsoft Windows",
  "settlers-2": "MS-DOS",
  "ja2-stracciatella": "MS-DOS",
  "isle-portable": "Microsoft Windows",
  trx: "MS-DOS",
  "wipeout-rewrite": "PlayStation",
  librelancer: "Microsoft Windows",
  "open-tes-arena": "MS-DOS",
  "space-cadet-pinball": "Microsoft Windows",
  wargus: "MS-DOS",
  openfodder: "MS-DOS",
  "reone-kotor": "Microsoft Windows",
  "sonic-3-air": "Sega Mega Drive / Genesis",
  "smw-rev": "Super Nintendo",
  "bt3-recomp": "PlayStation 2",
  donut: "Microsoft Windows",
  "dragon-ball-z-legacy-of-goku-recomp": "Game Boy Advance",
  "pinyon-shift": "Xbox 360",
  gears1: "Xbox 360",
  "metroid-nes-recomp": "Nintendo Entertainment System",
  "dkc2-recomp": "Super Nintendo",
  "dkc3-recomp": "Super Nintendo",
  "mega-man-x2-recomp": "Super Nintendo",
  "mario-kart-super-circuit-recomp": "Game Boy Advance",
  "ape-escape-recomp": "PlayStation",
  "tomba-recomp": "PlayStation",
  "tomba2-recomp": "PlayStation",
  "super-mario-bros-nes-recomp": "Nintendo Entertainment System",
  "links-awakening-recomp": "Game Boy / Game Boy Color",
  "oracle-recompiled": "Game Boy / Game Boy Color",
  "wind-waker-recomp": "GameCube",
  ringout: "GameCube",
  "drmario64-recomp-plus": "Nintendo 64",
  "snowboard-kids-2-recomp": "Nintendo 64",
  "mega-man-x4-recomp": "PlayStation",
  "mega-man-x5-recomp": "PlayStation",
  "mega-man-x6-recomp": "PlayStation",
  "ridge-racer-ps1-recomp": "PlayStation",
  "ridge-racer-revolution-recomp": "PlayStation",
  verdite2: "PlayStation",
  opengtps1: "PlayStation",
  "crash2-recomp": "PlayStation",
  "rage-racer-pc": "PlayStation",
  "flow-ps3-recomp": "PlayStation 3",
  "tokyo-jungle-recompiled": "PlayStation 3",
  "simpsons-arcade-ps3": "PlayStation 3",
  "youdontknowjack-recomp": "PlayStation 3",
  "mario-kart-64-recomp": "Nintendo 64",
  "star-fox-64-recomp": "Nintendo 64",
  "goemon-64-recompiled": "Nintendo 64",
  "dnzh-recomp": "Nintendo 64",
  reblue: "Xbox 360",
  "kameo-repowered": "Xbox 360",
  "tip-recomp": "Xbox 360",
  "re-cherry": "Xbox 360",
  "naughty-bear-restuff": "Xbox 360",
  renut: "Xbox 360",
  redahm: "Xbox 360",
  "duck-hunt-nes-recomp": "Nintendo Entertainment System",
  "dr-mario-nes-recomp": "Nintendo Entertainment System",
  "zelda-nes-recomp": "Nintendo Entertainment System",
  "faxanadu-recomp": "Nintendo Entertainment System",
  "yoshi-nes-recomp": "Nintendo Entertainment System",
  "yoshis-cookie-recomp": "Nintendo Entertainment System",
  "mega-man-3-nes-recomp": "Nintendo Entertainment System",
  "gumshoe-nes-recomp": "Nintendo Entertainment System",
  "pac-man-nes-recomp": "Nintendo Entertainment System",
  "smb-vanilla-port": "Nintendo Entertainment System",
  "zelda-alttp-snes-recomp": "Super Nintendo",
  "super-metroid-snes-recomp": "Super Nintendo",
  "sonic-1-genesis-recomp": "Sega Mega Drive / Genesis",
  "streets-of-rage-recomp": "Sega Mega Drive / Genesis",
  "tsumu-light-recomp": "PlayStation",
  "xenogears-recomp": "PlayStation",
  "ridge-racer-type-4-recomp": "PlayStation",
  "kings-field-recomp": "PlayStation",
  "mega-man-64-recomp": "Nintendo 64",
  "rocket-r": "Nintendo 64",
  "rush-2-recomp": "Nintendo 64",
  "chameleon-twist-2-recomp": "Nintendo 64",
  "superman-64-recomp": "Nintendo 64",
  "wcw-nwo-revenge-recomp": "Nintendo 64",
  "hamster-monogatari-64-recomp": "Nintendo 64",
  battleship: "Nintendo 64",
  "paper-mario-paperboat": "Nintendo 64",
  "animal-crossing-pc-port": "GameCube",
  "metroid-prime-port": "GameCube",
  "halo-ce-universal": "Xbox",
  "lost-odyssey-recomp": "Xbox 360",
  "dead-rising-2-case-zero-recomp": "Xbox 360",
  "ninja-gaiden-2-recomp": "Xbox 360",
  "perfect-dark-remaster-recomp": "Xbox 360",
  "sonic-free-riders-recomp": "Xbox 360",
  "superman-returns-recomp": "Xbox 360",
  "wet-recomp": "Xbox 360",
  "too-human-recomp": "Xbox 360",
  "spider-man-edge-of-time-recomp": "Xbox 360",
  "bloodborne-pc": "PlayStation 4",
  "pt-pc": "PlayStation 4",
  "silent-hill-pc": "PlayStation",
  "silent-engine": "PlayStation",
  "nfs-most-wanted-recomp": "Xbox 360",
  "final-fantasy-viii-recomp": "PlayStation",
  "final-fantasy-ix-recomp": "PlayStation",
  "fear-effect-recomp": "PlayStation",
  "g-police-recomp": "PlayStation",
  "ghost-in-the-shell-recomp": "PlayStation",
  "the-fifth-element-recomp": "PlayStation",
  einhander: "PlayStation",
  "tekken-3-recomp": "PlayStation",
  "guilty-gear-recomp": "PlayStation",
  "gundam-battle-master-recomp": "PlayStation",
  "gundam-battle-master-2-recomp": "PlayStation",
  "gundam-battle-assault-2-recomp": "PlayStation",
  "final-fantasy-tactics-recomp": "PlayStation",
  "syphon-filter-2-recompiled": "PlayStation",
  "pepsiman-recompiled": "PlayStation",
  "apocalypse-recomp": "PlayStation",
  "armored-core-recomp": "PlayStation",
  "armored-core-master-of-arena-recomp": "PlayStation",
  "armored-core-project-phantasma-recomp": "PlayStation",
  "azure-dreams-recomp": "PlayStation",
  "blood-omen-legacy-of-kain-recomp": "PlayStation",
  "bloody-roar-ii-recomp": "PlayStation",
  "brave-fencer-musashi-recomp": "PlayStation",
  "bushido-blade-2-recomp": "PlayStation",
  "colin-mcrae-rally-2-0-recomp": "PlayStation",
  "colony-wars-recomp": "PlayStation",
  "colony-wars-red-sun-recomp": "PlayStation",
  "crash-bandicoot-3-warped-recomp": "PlayStation",
  "destruction-derby-2-recomp": "PlayStation",
  "destruction-derby-raw-recomp": "PlayStation",
  "diablo-recomp": "PlayStation",
  "die-hard-trilogy-recomp": "PlayStation",
  "digimon-world-2-recomp": "PlayStation",
  "digimon-world-2003-recomp": "PlayStation",
  "dino-crisis-recomp": "PlayStation",
  "dragon-ball-z-ultimate-battle-22-recomp": "PlayStation",
  "driver-recomp": "PlayStation",
  "duke-nukem-land-of-the-babes-recomp": "PlayStation",
  "duke-nukem-time-to-kill-recomp": "PlayStation",
  "fade-to-black-recomp": "PlayStation",
  "fear-effect-2-retro-helix-recomp": "PlayStation",
  "fighting-force-recomp": "PlayStation",
  "future-cop-lapd-recomp": "PlayStation",
  "g-police-weapons-of-justice-recomp": "PlayStation",
  "galerians-recomp": "PlayStation",
  "in-cold-blood-recomp": "PlayStation",
  "incredible-crisis-recomp": "PlayStation",
  "jackie-chan-stuntmaster-recomp": "PlayStation",
  "jade-cocoon-recomp": "PlayStation",
  "kartia-recomp": "PlayStation",
  "koudelka-recomp": "PlayStation",
  "legacy-of-kain-soul-reaver-recomp": "PlayStation",
  "alien-resurrection-recomp": "PlayStation",
  "ace-combat-3-electrosphere-recomp": "PlayStation",
  "ace-combat-3-electrosphere-usa-recomp": "PlayStation",
  "alone-in-the-dark-the-new-nightmare-recomp": "PlayStation",
  "alundra-recomp": "PlayStation",
  "medievil-recomp": "PlayStation",
  "medievil-ii-recomp": "PlayStation",
  "mega-man-legends-recomp": "PlayStation",
  "mega-man-legends-2-recomp": "PlayStation",
  "men-in-black-the-game-recomp": "PlayStation",
  "metal-gear-solid-recomp": "PlayStation",
  "metal-slug-x-recomp": "PlayStation",
  "monster-rancher-recomp": "PlayStation",
  "monster-rancher-2-recomp": "PlayStation",
  "mortal-kombat-4-recomp": "PlayStation",
  "mortal-kombat-trilogy-recomp": "PlayStation",
  "nightmare-creatures-recomp": "PlayStation",
  "nightmare-creatures-ii-recomp": "PlayStation",
  "oddworld-abe-s-oddysee-recomp": "PlayStation",
  "parasite-eve-recomp": "PlayStation",
  "quake-ii-recomp": "PlayStation",
  "mdk-recomp": "PlayStation",
  "pro-pinball-timeshock-recomp": "PlayStation",
  "resident-evil-3-recomp": "PlayStation",
  "rival-schools-recomp": "PlayStation",
  "rival-schools-evolution-recomp": "PlayStation",
  "rollcage-stage-ii-recomp": "PlayStation",
  "silent-bomber-recomp": "PlayStation",
  "spider-man-recomp": "PlayStation",
  "spider-man-2-enter-electro-recomp": "PlayStation",
  "spyro-the-dragon-recomp": "PlayStation",
  "star-wars-episode-i-the-phantom-menace-recomp": "PlayStation",
  "suikoden-recomp": "PlayStation",
  "suikoden-ii-recomp": "PlayStation",
  "syphon-filter-3-recomp": "PlayStation",
  "tail-concerto-recomp": "PlayStation",
  "team-buddies-recomp": "PlayStation",
  "tenchu-stealth-assassins-recomp": "PlayStation",
  "the-lost-world-jurassic-park-special-edition-recomp": "PlayStation",
  "misadventures-of-tron-bonne-recomp": "PlayStation",
  "the-mummy-recomp": "PlayStation",
  "threads-of-fate-recomp": "PlayStation",
  "tokyo-highway-battle-recomp": "PlayStation",
  "tony-hawk-s-pro-skater-recomp": "PlayStation",
  "tony-hawk-s-pro-skater-2-recomp": "PlayStation",
  "tony-hawk-s-pro-skater-3-recomp": "PlayStation",
  "tony-hawk-s-pro-skater-4-recomp": "PlayStation",
  "valkyrie-profile-recomp": "PlayStation",
  "vampire-hunter-d-recomp": "PlayStation",
  "vib-ribbon-recomp": "PlayStation",
  "vigilante-8-recomp": "PlayStation",
  "wild-arms-recomp": "PlayStation",
  "wipeout-recomp": "PlayStation",
  "wipeout-xl-recomp": "PlayStation",
  "xena-warrior-princess-recomp": "PlayStation",
  "devil-dice-recomp": "PlayStation",
  "kula-world-recomp": "PlayStation",
  "fable-2-recomp": "Xbox 360",
  "the-darkness-recomp": "Xbox 360",
  "skate-3-recomp": "Xbox 360",
  "skate-3-mobile": "Xbox 360",
  "gta-iv-liberty-recomp": "Xbox 360",
  "eternal-sonata-reprise": "Xbox 360",
  "ace-combat-6-recomp": "Xbox 360",
  "condemned-2-recomp": "Xbox 360",
  "automobili-lamborghini-recomp": "Nintendo 64",
  "chameleon-twist-recomp": "Nintendo 64",
  "f-zero-x-recomp": "Nintendo 64",
  "mischief-makers-recomp": "Nintendo 64",
  "vpw2-recomp": "Nintendo 64",
  "vpw64-recomp": "Nintendo 64",
  "wcw-nwo-world-tour-recomp": "Nintendo 64",
  "wwf-no-mercy-recomp": "Nintendo 64",
  "wwf-wrestlemania-2000-recomp": "Nintendo 64",
  "aerogauge-recomp": "Nintendo 64",
  "snowboard-kids-recompiled": "Nintendo 64",
  "tetrisphere-recomp": "Nintendo 64",
  "body-harvest-recomp": "Nintendo 64",
  "rayman-2-n64-recomp": "Nintendo 64",
  "super-robot-wars-64-recomp": "Nintendo 64",
  "dragon-ball-z-legacy-of-goku-2-recomp": "Game Boy Advance",
  "dragon-ball-z-buus-fury-recomp": "Game Boy Advance",
  "warioware-twisted-recomp": "Game Boy Advance",
  "super-mario-advance-2-recomp": "Game Boy Advance",
  "super-mario-advance-4-recomp": "Game Boy Advance",
  "pokemon-firered-recomp": "Game Boy Advance",
  "pokemon-ruby-recomp": "Game Boy Advance",
  "pokemon-emerald-recomp": "Game Boy Advance",
  "mega-man-zero-recomp": "Game Boy Advance",
  "castlevania-circle-of-the-moon-recomp": "Game Boy Advance",
  "pokemon-mystery-dungeon-red-recomp": "Game Boy Advance",
  "summon-night-swordcraft-3-recomp": "Game Boy Advance",
  "pokemon-emerald-dual-screen": "Game Boy Advance",
  "burnout-3-recomp": "Xbox",
  "wreckless-recomp": "Xbox",
  "doa3-recomp": "Xbox",
  "doaxbv-re": "Xbox",
  "x-men-legends-recomp": "Xbox",
  "mario-party-4-recomp": "GameCube",
  "medal-of-honor-frontline-recomp": "GameCube",
  "star-fox-adventures-recomp": "GameCube",
  "super-mario-sunshine-pc": "GameCube",
  "super-mario-sunshine-android": "GameCube",
  "fatal-frame-recomp": "PlayStation 2",
  "street-fighter-iii-3rd-strike-3sx": "PlayStation 2",
  "god-of-war-recomp": "PlayStation 2",
  "pgr4-recomp": "Xbox 360",
  "sega-superstars-tennis-rematch": "Xbox 360",
  "tony-hawks-project-8-recomp": "Xbox 360",
  "wwe-smackdown-vs-raw-2007-recomp": "Xbox 360",
  "deadly-premonition-recomp": "Xbox 360",
  "dragon-ball-z-budokai-hd": "Xbox 360",
  "dragon-ball-z-budokai-3-hd": "Xbox 360",
  "forza-motorsport-4-recomp": "Xbox 360",
  "exit-recomp": "Xbox 360",
  "ufc-undisputed-3-recomp": "Xbox 360",
  "guitar-hero-warriors-of-rock-recomp": "Xbox 360",
  "crackdown-recomp": "Xbox 360",
  "halo-3-recomp": "Xbox 360",
  "dead-rising-2-case-west-recomp": "Xbox 360",
  "saints-row-recomp": "Xbox 360",
  "dantes-inferno-recomp": "Xbox 360",
  "dantes-inferno-android": "Xbox 360",
  "daytona-usa-recomp": "Xbox 360",
  "dodonpachi-saidaioujou-recomp": "Xbox 360",
  "crackdown-2-recomp": "Xbox 360",
  "test-drive-unlimited-recomp": "Xbox 360",
  "dragon-ball-raging-blast-2-recomp": "Xbox 360",
  "midnight-club-la-recomp": "Xbox 360",
  "burnout-revenge-recomp": "Xbox 360",
  "conan-2007-recomp": "Xbox 360",
  "rumble-roses-xx-recomp": "Xbox 360",
  "call-of-duty-3-recomp": "Xbox 360",
  "project-1944-recomp": "Xbox 360",
  "rayman-origins-recomp": "Xbox 360",
  "viva-pinata-recomp": "Xbox 360",
  "infinite-undiscovery-recomp": "Xbox 360",
  "crash-of-the-titans-recomp": "Xbox 360",
  "call-of-duty-mw2-recomp": "Xbox 360",
  "blue-droid": "Xbox 360",
  "x-men-destiny-recomp": "Xbox 360",
  "army-of-two-recomp": "Xbox 360",
  "gears-of-war-2-hollow": "Xbox 360",
  "gears-of-war-3-jacinto": "Xbox 360",
  "minecraft-x360-ios": "Xbox 360",
  "jazz2-native": "Microsoft Windows",
  sdlpal: "MS-DOS",
  nfsiise: "Microsoft Windows",
  gish: "Microsoft Windows",
  mbhaxe: "Microsoft Windows",
  openjkdf2: "Microsoft Windows",
  "cs16-client": "Microsoft Windows",
  "tf15-client": "Microsoft Windows",
  "barony-android": "Microsoft Windows",
  "god-of-thunder-android": "MS-DOS",
  "pinball-fantasies-android": "MS-DOS",
  unciv: "Microsoft Windows",
  "srb2-android": "Microsoft Windows",
  "ring-racers-android": "Microsoft Windows",
  "fear-and-hunger-android": "Microsoft Windows",
  "fear-and-hunger-termina-android": "Microsoft Windows",
  "ftl-pocket-wormhole": "Microsoft Windows",
  "project-zomboid-android": "Microsoft Windows",
  "rimworld-android": "Microsoft Windows",
  "prison-architect-android": "Microsoft Windows",
  "stardew-cinderbox": "Microsoft Windows",
  "post-void-mobile": "Microsoft Windows",
  "serious-sam-android": "Microsoft Windows",
  "unreal-tournament-android": "Microsoft Windows",
  "zuma-deluxe-android": "Microsoft Windows",
  "nethack-android": "Microsoft Windows",
  "nfs3-android": "Microsoft Windows",
  "buckshot-roulette-mobile": "Microsoft Windows",
  "starbound-android": "Microsoft Windows",
  "amethyst-android": "Microsoft Windows",
  "unnethack-android": "MS-DOS",
  "slashem-android": "MS-DOS",
  amphitere: "MS-DOS",
  "pokerogue-app": "Microsoft Windows",
  "repo-ev-r": "Microsoft Windows",
  "sonic-r-android": "Sega Saturn",
  "voyager-elite-force-android": "Microsoft Windows",
  "voyager-elite-force-holomatch": "Microsoft Windows",
  "ufo50-android": "Microsoft Windows",
  "warcraft-orcs-and-humans-android": "MS-DOS",
  "broforce-android": "Microsoft Windows",
  "celeste-android": "Microsoft Windows",
  "pokewilds-android": "Microsoft Windows",
  "touhou-6-android": "Microsoft Windows",
  valdroid: "Microsoft Windows",
};
