import type { Port } from "@/lib/ports/schema";

export const originalSystemById: Record<Port["id"], string> = {
  sm64ex: "Nintendo 64",
  "ship-of-harkinian": "Nintendo 64",
  "2ship2harkinian": "Nintendo 64",
  "star-rod": "Nintendo 64",
  "open-lara": "PlayStation / Sega Saturn",
  devilutionx: "MS-DOS",
  "nxengine-evo": "Microsoft Windows",
  "daggerfall-unity": "MS-DOS",
  openmw: "Microsoft Windows",
  "xash3d-fwgs": "Microsoft Windows",
  vkquake: "MS-DOS",
  "yamagi-quake2": "Microsoft Windows",
  gzdoom: "MS-DOS",
  eduke32: "MS-DOS",
  openxcom: "MS-DOS / Amiga",
  openttd: "MS-DOS / Amiga",
  openrct2: "Microsoft Windows",
  "fallout1-ce": "MS-DOS",
  "fallout2-ce": "Microsoft Windows",
  openjk: "Microsoft Windows",
  gemrb: "Microsoft Windows / MS-DOS",
  "sonic-1-2-2013": "Sega Mega Drive / Genesis",
  "sonic-mania-decomp": "Microsoft Windows",
  "downpour-recomp": "Xbox 360",
  wiicompiled: "Wii",
  openra: "MS-DOS",
  starship: "Nintendo 64",
  spaghettikart: "Nintendo 64",
  lighthouse: "Nintendo 64",
  "goldeneye-64-recompiled": "Nintendo 64",
  "dk64-recompiled": "Nintendo 64",
  "wave-race-64-recompiled": "Nintendo 64",
  "road-rash-64-recompiled": "Nintendo 64",
  "f-zero-snes-recompiled": "Super Nintendo",
  "dkc-recompiled": "Super Nintendo",
  "metroid-prime-hunters-recompiled": "Nintendo DS",
  "perfect-dark-dabs-mod": "Nintendo 64",
  triaevum: "Nintendo 3DS",
  "prboom-plus-rt": "MS-DOS",
  "doom3-dude": "Microsoft Windows",
  "unleashed-recompiled": "Xbox 360",
  dusklight: "GameCube",
  "melee-native": "GameCube",
  pikmin: "Nintendo GameCube",
  petari: "Wii",
  "ctr-native": "PlayStation",
  pokered: "Game Boy",
  zelda3: "Super Nintendo",
  "dkr-r": "Nintendo 64",
  "symphony-recomp": "PlayStation",
  "super-mario-bros-remastered": "Nintendo Entertainment System",
  "crash-bandicoot": "PlayStation",
  "minish-cap": "Game Boy Advance",
  "marathon-recomp": "Xbox 360",
};
