import type { Port } from "@/lib/ports/schema";

export const openMohaa: Port = {
  schema: "port",
  id: "openmohaa",
  title: "OpenMoHAA",
  game: "Medal of Honor: Allied Assault",
  developers: ["OpenMoHAA Team"],
  publisher: "Electronic Arts",
  originalYear: 2002,
  genre: "shooter",
  openSource: true,
  portType: "source-port",
  platforms: ["windows", "linux", "macos"],
  status: "alpha",
  release: { version: "0.82.1", date: "2025-08-05" },
  sources: ["https://github.com/openmoh/openmohaa"],
  website: "https://docs.openmohaa.org/",
  license: { spdx: "GPL-2.0" },
  verified: true,
  verifiedAt: "2026-10-01",
  originalSystem: "Microsoft Windows",
  features: ["Reimplementation of the id Tech 3 era engine", "Cross-platform desktop builds"],
  notes: "Open source continuation of the Medal of Honor: Allied Assault codebase.",
};
